### ISSUE TITLE
Crash in Anki 2.1.50 with Qt 6.2.2

### ISSUE THREAD

**Issue by homocomputeris** [Ajatt-Tools/PitchAccent#2]
I've tried to use Anki built with Qt6 (which, as far as I understand, will eventually replace Qt5).

This what happens when I try to open Pitch Accent Options:
```
Anki 2.1.50 (2df3698e) Python 3.10.1 Qt 6.2.2 PyQt 6.2.2
Platform: Linux
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2021-12-30 23:04:40
Probable reason: ⁨AJT Pitch Accent⁩

Caught exception:
Traceback (most recent call last):
  File "/home/user/.local/share/Anki2/addons21/1225470483/options.py", line 240, in open_options
    dialog = SettingsDialog(mw)
  File "/home/user/.local/share/Anki2/addons21/1225470483/options.py", line 170, in __init__
    self.list_edits = self.create_list_edits()
  File "/home/user/.local/share/Anki2/addons21/1225470483/options.py", line 176, in create_list_edits
    'note_types': NoteTypesListEdit(self),
  File "/home/user/.local/share/Anki2/addons21/1225470483/options.py", line 132, in __init__
    super(NoteTypesListEdit, self).__init__(
  File "/home/user/.local/share/Anki2/addons21/1225470483/options.py", line 65, in __init__
    self.list_widget = self.create_list_widget(items)
  File "/home/user/.local/share/Anki2/addons21/1225470483/options.py", line 71, in create_list_widget
    list_widget.setSizeAdjustPolicy(QListWidget.AdjustToContents)
AttributeError: type object 'QListWidget' has no attribute 'AdjustToContents'
```
I've also reported the issue to the forums https://forums.ankiweb.net/t/add-on-issues-with-anki-2-1-50-beta/15631/18?u=homocomputeris
dae suggests:

> The compat shims can’t cover cases where the enum was defined in a parent class. It needs to be changed to something like QSizePolicy.AdjustToContents.

**Comment by tatsumoto-ren** [comment]
Yes, it's unfortunate.
